language: go

sudo: required
dist: trusty

before_install:
  - cd $HOME
  - TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/nemosupremo/vault-gatekeeper
  - cd $HOME/gopath/src/github.com/nemosupremo/vault-gatekeeper

#cache:
#  directories:

services:
  - docker

env:
  global:
    - GOMAXPROCS=2

go:
  - '1.10'

before_install:
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure -v -vendor-only

script:
  - set -e
  - docker run -d -p 8200:8200 --hostname vault --name vault vault server -dev -dev-root-token-id=vault-gatekeeper-test-token-id
  - bash integration.sh
  - go vet -composites=false ./...

after_script:
  - docker stop vault
  - docker rm vault

#notifications:
#  - email: false